config/routes.rb
Rails.application.routes.draw do
  get 'kittens/index'
  get 'kittens/show'
  get 'kittens/new'
  get 'kittens/create'
  get 'kittens/edit'
  get 'kittens/update'
  get 'kittens/destroy'
  delete 'delete_kitten', to: "kittens#destroy"
  delete 'delete_kitten', to: "kittens#destroy"
  root 'kittens#index'
 resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  require 'rest-client'
  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html #normal html display index.html.erb
      format.xml {render xml: @kittens}
      format.json {render json: @kittens}
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.create(kitten_params)
    if @kitten.save
      flash[:succes] = "Kitten created successfully"
      redirect_to root_url
    else
      flash[:notice] = "Unable to create kitten please try again"
      render 'new'
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
    
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update_attributes(kitten_params)
      flash[:success] = "Kitten updated successfully"
      redirect_to @kitten
    else
      flash[:notice] = "Kitten not updated"
      render 'edit'
    end
  end

  def destroy
    Kitten.find(params[:id]).destroy
    flash[:success] = "Kitten deleted"
    redirect_to root_url
  end

  private 

  def kitten_params
    params.require(:kitten).permit(:name,:age,:cuteness,:softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_for(@kitten) do |f| %>
    <div class="form-group form-group-lg">
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control" %>
    </div>
    <div class="form-group form-group-lg">
    <%= f.label :age %>
    <%= f.text_field :age, class:"form-control" %>
    </div>
    <div class="form-group form-group-lg">
    <%= f.label :cuteness %>
    <%= f.text_field :cuteness, class:"form-control" %>
    </div>
    <div class="form-group  form-group-lg">
    <%= f.label :softness %>
    <%= f.text_field :softness, class:"form-control" %>
    </div>

    <%= f.submit yield(:button_text), class: "btn btn-success btn-lg" %>
<% end %>

app/views/kittens/create.html.erb
<h1>Kittens#create</h1>
<p>Find me in app/views/kittens/create.html.erb</p>

app/views/kittens/destroy.html.erb
<h1>Kittens#destroy</h1>
<p>Find me in app/views/kittens/destroy.html.erb</p>

app/views/kittens/edit.html.erb
<% provide(:button_text, "Update kitten ") %>

<div class="row" >
   <div class="col-md-6 col-md-offset-3">
   <h1>Add a kitten</h1>
   <% if @kitten %>
       <%= render 'form'%>
       <p><%= link_to 'Delete', delete_kitten_path(id: @kitten.id), method: :delete, data: {confirm: "Are you sure you want to delete this kitten?"} %></p>
      <% else %> 
      <p>Kitten not found </p>
      <% end %>
   </div>
</div>

app/views/kittens/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
        <h1>Kittens</h1>
     <div class = "table-responsive">
       <table class="table table-striped table-hover">
           <thead>
               <tr>
                   <th>Name</th>
                   <th>Age</th>
                   <th>Cuteness</th>
                   <th>Softness</th>
                   <th>Action</th>
               </tr>
           </thead>
           <tbody>
                <% if @kittens.any? %>
                   <% @kittens.each do |kitten|%>
                   <tr>
                       <td><%= kitten.name %></td>
                       <td><%= kitten.age %></td>
                       <td><%= kitten.cuteness %></td>
                       <td><%= kitten.softness %></td>
                       <td><%= link_to 'Delete', delete_kitten_path(id: kitten.id), method: :delete, data: {confirm: "Are you sure you want to delete this kitten?"} %><i class="fas fa-trash-alt"></i></td>
                   </tr>
                   <% end %>
                   <%  else %>
                   <p>No  Kitten available</p>
                <% end%>
           </tbody>
       </table>
     </div>
  </div>
</div>

app/views/kittens/new.html.erb
<% provide(:button_text, "Create a kitten ") %>
<div class="row" >
   <div class="col-md-6 col-md-offset-3">
   <h1>Add a kitten</h1>
       <%= render 'form'%>
   </div>
</div>

app/views/kittens/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
        <h1>Kitten</h1>
     <div class = "table-responsive">
       <table class="table table-striped table-hover">
           <thead>
               <tr>
                   <th>Name</th>
                   <th>Age</th>
                   <th>Cuteness</th>
                   <th>Softness</th>
                   <th>Softness</th>
               </tr>
           </thead>
           <tbody>
                <% if @kitten %>
                   <tr>
                       <td><%= @kitten.name %></td>
                       <td><%= @kitten.age %></td>
                       <td><%= @kitten.cuteness %></td>
                       <td><%= @kitten.softness %></td>
                       <td><%= link_to 'Delete', delete_kitten_path(id: @kitten.id), method: :delete, data: {confirm: "Are you sure you want to delete this kitten?"} %><i class="fas fa-trash-alt"></i></td>
                   </tr>
                <% end%>
           </tbody>
       </table>
     </div>
  </div>
</div>

app/views/kittens/update.html.erb
<h1>Kittens#update</h1>
<p>Find me in app/views/kittens/update.html.erb</p>

app/views/layouts/_shim.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>APIs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
  <div class="container">
  <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %>
    <%= yield %>
  </div>
  </body>
</html>